# This is a basic workflow to help you get started with Actions

name: APIM Prod Contoso APIs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: 
    - 'apis/**'
    #- '!servless-devops/**/README.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Prod-Apims-Apis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      resourceGroup: apim-prod-contoso-rg
      ApimServiceName: apims-prod-contoso
      repoUrl: https://raw.githubusercontent.com/romerve/rvlabs-apim-devops
      repoBranch: ${GITHUB_REF##*/}
      repoApimPath: apis

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    # Azure login
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_APIMS_CONTOSO }}

    # ARM deployment tasks  
    - name: Deploy APIs
      working-directory: ./apis
      env:
        LinkedTemplatesBaseUrl: ${{ env.repoUrl }}/${{ env.repoBranch }}/${{ env.repoApimPath }}
        deploymentName: --name GH_dev_deployment_apim
        rg: --resource-group ${{ env.resourceGroup }}
        apiNamePrefix: apim-contoso
      run: |
        echo $apiNamePrefix
        for f in *; do
          if [[ -d ${f} && ! -L ${f} ]]; then
            echo "Deploying API: $f"
            az deployment group create $deploymentName $rg --template-file ./$f/arm/$apiNamePrefix-master.template.json --parameters ./$f/arm/$apiNamePrefix-parameters.json --parameters ApimServiceName=${{ env.ApimServiceName }} LinkedTemplatesBaseUrl=${{ env.LinkedTemplatesBaseUrl }}/$f/arm
          fi
        done